import "./globals.css";
import { Toaster } from "react-hot-toast";
import Providers from "./Providers";
import { headers } from "next/headers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  let userId = null 
  let Name = null 
  let Email = null

  try {
    const headersList = await headers()
    userId = headersList.get("x-user-id")
    Name = headersList.get("x-user-name")
    Email = headersList.get("x-user-email")
  } catch (error) {
    console.log("Headers Not Available",error.message)
  }

  // console.log("Login UserId in Layout==", userId)

  return (
    <html lang="en">
      <body>
        <Toaster/>
        <Providers initialUser = {{userId,Name,Email}}>
          {children}
        </Providers>
      </body>
    </html>
  );
}